import type { PriorAuthCase, AuditEvent, CaseStage } from "./types";

// Deterministic clock so server render and client hydration agree.
const BASE = Date.parse("2026-06-04T09:30:00.000Z");
function ago(minutes: number): string {
  return new Date(BASE - minutes * 60_000).toISOString();
}
function ahead(minutes: number): string {
  return new Date(BASE + minutes * 60_000).toISOString();
}

let auditSeq = 0;
function ev(
  minutes: number,
  actorKind: AuditEvent["actorKind"],
  actor: string,
  action: string,
  detail: string,
  stage: CaseStage
): AuditEvent {
  auditSeq += 1;
  return {
    id: `aud-${auditSeq}`,
    at: ago(minutes),
    actorKind,
    actor,
    action,
    detail,
    stage,
  };
}

export const SEED_CASES: PriorAuthCase[] = [
  {
    id: "PA-20492",
    title: "Lumbar spine MRI",
    patient: { name: "Dana Whitfield", mrn: "MRN-558120", dob: "1971-03-14", age: 55, sex: "F" },
    procedure: { cpt: "72148", name: "MRI lumbar spine without contrast", site: "Lumbar spine" },
    primaryDiagnosis: { icd10: "M54.16", name: "Radiculopathy, lumbar region" },
    payer: { id: "meridian", name: "Meridian Health Plan", plan: "Meridian PPO Select" },
    referringProvider: { name: "Dr. Lena Ortiz", npi: "1487209365", specialty: "Family Medicine" },
    urgency: "routine",
    stage: "intake",
    runState: "running",
    createdAt: ago(22),
    updatedAt: ago(20),
    slaDueAt: ahead(60 * 46),
    coordinator: "Priya Nair",
    clinician: "Dr. Marcus Bell",
    estimatedValue: 1450,
    evidence: { status: "pending", narrative: "", diagnoses: [], priorTreatments: [], documents: [] },
    ruleMatch: {
      status: "pending",
      payerPolicy: "Advanced Imaging - MRI of the Spine",
      policyId: "MERIDIAN-RAD-014",
      confidence: 0,
      criteria: [],
      missingItems: [],
      readiness: 0,
      framework: "CrewAI payer-rules crew (UiPath governed)",
    },
    submission: { status: "not_submitted" },
    decision: { outcome: "pending" },
    appeal: { status: "none", citations: [] },
    humanTasks: [],
    auditTrail: [
      ev(22, "robot", "Intake Robot (RPA)", "Case opened", "Referral PDF ingested from intake inbox and parsed into a Maestro Case.", "intake"),
      ev(20, "system", "Maestro Case Manager", "Stage set: Intake", "Case manager agent assigned coordinator Priya Nair and clinician Dr. Marcus Bell.", "intake"),
    ],
  },
  {
    id: "PA-20481",
    title: "Lumbar spine MRI",
    patient: { name: "Marcus Adeyemi", mrn: "MRN-449087", dob: "1968-09-02", age: 57, sex: "M" },
    procedure: { cpt: "72148", name: "MRI lumbar spine without contrast", site: "Lumbar spine" },
    primaryDiagnosis: { icd10: "M51.16", name: "Intervertebral disc disorders with radiculopathy, lumbar region" },
    payer: { id: "meridian", name: "Meridian Health Plan", plan: "Meridian PPO Select" },
    referringProvider: { name: "Dr. Aisha Rahman", npi: "1730284417", specialty: "Orthopedics" },
    urgency: "urgent",
    stage: "rule_match",
    runState: "running",
    createdAt: ago(180),
    updatedAt: ago(8),
    slaDueAt: ahead(60 * 20),
    coordinator: "Priya Nair",
    clinician: "Dr. Marcus Bell",
    estimatedValue: 1450,
    evidence: {
      status: "extracted",
      model: "Claude via UiPath AI Trust Layer",
      extractedAt: ago(40),
      narrative:
        "57-year-old male with 9 weeks of progressive low back pain radiating to the left lower extremity. Failed 8 weeks of physical therapy and a course of NSAIDs. Exam shows positive straight-leg raise on the left and diminished ankle reflex. No bowel or bladder dysfunction.",
      diagnoses: [
        { icd10: "M51.16", name: "Disc disorder with radiculopathy, lumbar" },
        { icd10: "M54.16", name: "Radiculopathy, lumbar region" },
      ],
      priorTreatments: [
        { id: "t1", label: "Physical therapy", value: "8 weeks, documented in note 2026-04-18", source: "PT discharge summary", confidence: 0.96 },
        { id: "t2", label: "NSAID trial", value: "Naproxen 500mg BID x 4 weeks", source: "Medication list", confidence: 0.93 },
      ],
      documents: [
        { id: "d1", label: "Neuro exam", value: "Positive SLR left, diminished ankle reflex", source: "Progress note 2026-05-28", confidence: 0.9 },
        { id: "d2", label: "Pain duration", value: "9 weeks, progressive", source: "Progress note 2026-05-28", confidence: 0.95 },
      ],
    },
    ruleMatch: {
      status: "matched",
      payerPolicy: "Advanced Imaging - MRI of the Spine",
      policyId: "MERIDIAN-RAD-014",
      framework: "CrewAI payer-rules crew (UiPath governed)",
      confidence: 0.88,
      readiness: 67,
      matchedAt: ago(8),
      criteria: [
        { id: "c1", text: "Conservative therapy of at least 6 weeks documented and failed", status: "met", rationale: "8 weeks of PT plus NSAID trial documented.", citation: "Meridian Medical Policy RAD-014 section 3.2" },
        { id: "c2", text: "Neurologic deficit or red-flag symptom documented", status: "met", rationale: "Positive SLR and diminished reflex on exam.", citation: "Meridian Medical Policy RAD-014 section 3.3" },
        { id: "c3", text: "Recent radiographs (X-ray) on file within 60 days", status: "missing", rationale: "No lumbar X-ray found in the record within the last 60 days.", citation: "Meridian Medical Policy RAD-014 section 4.1" },
      ],
      missingItems: ["Lumbar spine X-ray within 60 days (or documented red-flag exception)"],
    },
    submission: { status: "not_submitted", portal: "Meridian Provider Portal", robot: "Portal Submit Robot" },
    decision: { outcome: "pending" },
    appeal: { status: "none", citations: [] },
    humanTasks: [],
    auditTrail: [
      ev(180, "coordinator", "Priya Nair", "Case opened", "Referral entered for urgent lumbar MRI.", "intake"),
      ev(40, "agent", "Clinical Evidence Agent (Agent Builder)", "Evidence extracted", "Pulled diagnoses, 8 weeks PT, NSAID trial, and neuro exam from the chart using context grounding.", "evidence"),
      ev(8, "agent", "Payer-Rules Agent (CrewAI)", "Policy matched", "Evaluated against Meridian RAD-014. 2 of 3 criteria met, missing recent lumbar X-ray.", "rule_match"),
      ev(8, "system", "Maestro Case Manager", "Missing-evidence flag raised", "Case held before submission until X-ray is attached or red-flag exception documented.", "rule_match"),
    ],
  },
  {
    id: "PA-20477",
    title: "Brain MRI",
    patient: { name: "Sofia Marchetti", mrn: "MRN-771043", dob: "1990-11-21", age: 35, sex: "F" },
    procedure: { cpt: "70551", name: "MRI brain without contrast", site: "Brain" },
    primaryDiagnosis: { icd10: "G43.909", name: "Migraine, unspecified, not intractable" },
    payer: { id: "northstar", name: "NorthStar Mutual", plan: "NorthStar HMO Plus" },
    referringProvider: { name: "Dr. Omar Haddad", npi: "1902837465", specialty: "Neurology" },
    urgency: "routine",
    stage: "rule_match",
    runState: "running",
    createdAt: ago(95),
    updatedAt: ago(12),
    slaDueAt: ahead(60 * 30),
    coordinator: "Devon Clarke",
    clinician: "Dr. Helen Yoo",
    estimatedValue: 1180,
    evidence: {
      status: "extracted",
      model: "Claude via UiPath AI Trust Layer",
      extractedAt: ago(30),
      narrative:
        "35-year-old female with new-onset headaches over 5 weeks, now with transient visual aura and one episode of unilateral weakness. Prior CT head without contrast 3 weeks ago was unremarkable. Trial of sumatriptan with partial response.",
      diagnoses: [
        { icd10: "G43.909", name: "Migraine, unspecified" },
        { icd10: "R51.9", name: "Headache, unspecified" },
      ],
      priorTreatments: [
        { id: "t1", label: "Sumatriptan trial", value: "50mg PRN, partial response", source: "Medication list", confidence: 0.92 },
      ],
      documents: [
        { id: "d1", label: "Prior CT head", value: "Unremarkable, 2026-05-12", source: "Radiology report", confidence: 0.97 },
        { id: "d2", label: "Neuro exam", value: "Transient unilateral weakness, visual aura", source: "Neurology note", confidence: 0.88 },
      ],
    },
    ruleMatch: {
      status: "matched",
      payerPolicy: "MRI of the Brain - Medical Necessity",
      policyId: "NORTHSTAR-NEU-009",
      framework: "CrewAI payer-rules crew (UiPath governed)",
      confidence: 0.94,
      readiness: 100,
      matchedAt: ago(12),
      criteria: [
        { id: "c1", text: "Documented new or progressive neurologic symptoms", status: "met", rationale: "New aura and transient unilateral weakness.", citation: "NorthStar Policy NEU-009 section 2.1" },
        { id: "c2", text: "Prior CT or imaging reviewed and documented", status: "met", rationale: "Prior CT head documented 3 weeks ago.", citation: "NorthStar Policy NEU-009 section 2.4" },
        { id: "c3", text: "Failure of initial management where applicable", status: "met", rationale: "Sumatriptan trial with partial response.", citation: "NorthStar Policy NEU-009 section 3.0" },
      ],
      missingItems: [],
    },
    submission: { status: "not_submitted", portal: "NorthStar Provider Portal", robot: "Portal Submit Robot" },
    decision: { outcome: "pending" },
    appeal: { status: "none", citations: [] },
    humanTasks: [
      {
        id: "ht-20477-1",
        title: "Approve submission to NorthStar",
        description: "All 3 medical-necessity criteria met. Clinician sign-off required before the RPA robot submits.",
        kind: "submission_approval",
        assignee: "Dr. Helen Yoo",
        status: "open",
        createdAt: ago(12),
      },
    ],
    auditTrail: [
      ev(95, "coordinator", "Devon Clarke", "Case opened", "Referral entered for brain MRI.", "intake"),
      ev(30, "agent", "Clinical Evidence Agent (Agent Builder)", "Evidence extracted", "Pulled neuro symptoms, prior CT, and medication trial.", "evidence"),
      ev(12, "agent", "Payer-Rules Agent (CrewAI)", "Policy matched", "All 3 criteria met against NorthStar NEU-009. Readiness 100%.", "rule_match"),
      ev(12, "system", "Maestro Case Manager", "Human task created", "Submission approval routed to Dr. Helen Yoo.", "rule_match"),
    ],
  },
  {
    id: "PA-20468",
    title: "Knee arthroscopy",
    patient: { name: "Theo Nakamura", mrn: "MRN-330912", dob: "1985-06-30", age: 40, sex: "M" },
    procedure: { cpt: "29881", name: "Arthroscopy, knee, with meniscectomy", site: "Right knee" },
    primaryDiagnosis: { icd10: "M23.205", name: "Derangement of meniscus, right knee" },
    payer: { id: "gulfcoast", name: "Gulf Coast Care", plan: "Gulf Coast EPO" },
    referringProvider: { name: "Dr. Rachel Stern", npi: "1556372819", specialty: "Orthopedic Surgery" },
    urgency: "routine",
    stage: "submission",
    runState: "running",
    createdAt: ago(260),
    updatedAt: ago(15),
    slaDueAt: ahead(60 * 12),
    coordinator: "Devon Clarke",
    clinician: "Dr. Marcus Bell",
    estimatedValue: 6200,
    evidence: {
      status: "extracted",
      model: "Claude via UiPath AI Trust Layer",
      extractedAt: ago(120),
      narrative:
        "40-year-old male with mechanical right knee pain, locking, and a confirmed medial meniscus tear on MRI. Completed 7 weeks of physical therapy and a corticosteroid injection without lasting relief.",
      diagnoses: [{ icd10: "M23.205", name: "Derangement of meniscus, right knee" }],
      priorTreatments: [
        { id: "t1", label: "Physical therapy", value: "7 weeks", source: "PT note", confidence: 0.95 },
        { id: "t2", label: "Corticosteroid injection", value: "1 injection, 2026-04-02", source: "Procedure note", confidence: 0.94 },
      ],
      documents: [
        { id: "d1", label: "Knee MRI", value: "Medial meniscus tear confirmed", source: "Radiology report", confidence: 0.98 },
        { id: "d2", label: "Functional limitation", value: "Locking, instability on exam", source: "Ortho note", confidence: 0.9 },
      ],
    },
    ruleMatch: {
      status: "matched",
      payerPolicy: "Knee Arthroscopy and Joint Procedures",
      policyId: "GULFCOAST-ORT-022",
      framework: "CrewAI payer-rules crew (UiPath governed)",
      confidence: 0.96,
      readiness: 100,
      matchedAt: ago(110),
      criteria: [
        { id: "c1", text: "MRI or imaging confirming structural pathology", status: "met", rationale: "MRI confirms medial meniscus tear.", citation: "Gulf Coast Policy ORT-022 section 1.2" },
        { id: "c2", text: "Conservative therapy trial of 6 weeks documented", status: "met", rationale: "7 weeks PT plus injection.", citation: "Gulf Coast Policy ORT-022 section 2.1" },
        { id: "c3", text: "Functional limitation documented on exam", status: "met", rationale: "Locking and instability documented.", citation: "Gulf Coast Policy ORT-022 section 2.3" },
      ],
      missingItems: [],
    },
    submission: {
      status: "submitted",
      portal: "Gulf Coast Provider Portal",
      robot: "Portal Submit Robot",
      portalRef: "GCC-AUTH-558231",
      submittedAt: ago(15),
    },
    decision: { outcome: "pending" },
    appeal: { status: "none", citations: [] },
    humanTasks: [
      {
        id: "ht-20468-1",
        title: "Approve submission to Gulf Coast",
        description: "Submission approval signed by clinician.",
        kind: "submission_approval",
        assignee: "Dr. Marcus Bell",
        status: "approved",
        createdAt: ago(100),
        decidedAt: ago(95),
        note: "Criteria met, imaging confirms tear. Approved for submission.",
      },
    ],
    auditTrail: [
      ev(260, "coordinator", "Devon Clarke", "Case opened", "Referral entered for knee arthroscopy.", "intake"),
      ev(120, "agent", "Clinical Evidence Agent (Agent Builder)", "Evidence extracted", "Pulled MRI findings, PT, and injection history.", "evidence"),
      ev(110, "agent", "Payer-Rules Agent (CrewAI)", "Policy matched", "All criteria met against Gulf Coast ORT-022.", "rule_match"),
      ev(95, "clinician", "Dr. Marcus Bell", "Submission approved", "Clinician signed off at the human gate.", "submission"),
      ev(15, "robot", "Portal Submit Robot (RPA)", "Submitted to portal", "Filed to Gulf Coast portal, reference GCC-AUTH-558231. Polling for status.", "submission"),
    ],
  },
  {
    id: "PA-20455",
    title: "Brain MRI (denied, appeal)",
    patient: { name: "Eleanor Briggs", mrn: "MRN-220471", dob: "1959-02-08", age: 67, sex: "F" },
    procedure: { cpt: "70553", name: "MRI brain with and without contrast", site: "Brain" },
    primaryDiagnosis: { icd10: "R51.9", name: "Headache, unspecified" },
    payer: { id: "northstar", name: "NorthStar Mutual", plan: "NorthStar HMO Plus" },
    referringProvider: { name: "Dr. Omar Haddad", npi: "1902837465", specialty: "Neurology" },
    urgency: "urgent",
    stage: "appeal",
    runState: "waiting_human",
    createdAt: ago(60 * 26),
    updatedAt: ago(6),
    slaDueAt: ahead(60 * 8),
    coordinator: "Devon Clarke",
    clinician: "Dr. Helen Yoo",
    estimatedValue: 1320,
    evidence: {
      status: "extracted",
      model: "Claude via UiPath AI Trust Layer",
      extractedAt: ago(60 * 25),
      narrative:
        "67-year-old female with progressive headaches, new papilledema on fundoscopic exam, and a focal neurologic deficit. Prior CT showed a nonspecific finding warranting MRI characterization. This presentation carries red-flag features that meet medical-necessity criteria.",
      diagnoses: [
        { icd10: "R51.9", name: "Headache, unspecified" },
        { icd10: "H47.10", name: "Papilledema, unspecified" },
      ],
      priorTreatments: [
        { id: "t1", label: "Analgesic trial", value: "Acetaminophen, no relief", source: "Medication list", confidence: 0.9 },
      ],
      documents: [
        { id: "d1", label: "Fundoscopic exam", value: "Papilledema present", source: "Neuro note", confidence: 0.93 },
        { id: "d2", label: "Prior CT", value: "Nonspecific finding, recommend MRI", source: "Radiology report", confidence: 0.95 },
        { id: "d3", label: "Focal deficit", value: "Right facial droop noted", source: "Neuro note", confidence: 0.89 },
      ],
    },
    ruleMatch: {
      status: "matched",
      payerPolicy: "MRI of the Brain - Medical Necessity",
      policyId: "NORTHSTAR-NEU-009",
      framework: "CrewAI payer-rules crew (UiPath governed)",
      confidence: 0.97,
      readiness: 100,
      matchedAt: ago(60 * 24),
      criteria: [
        { id: "c1", text: "Documented new or progressive neurologic symptoms", status: "met", rationale: "Papilledema and focal deficit documented.", citation: "NorthStar Policy NEU-009 section 2.1" },
        { id: "c2", text: "Prior CT or imaging reviewed and documented", status: "met", rationale: "Prior CT documented with recommendation for MRI.", citation: "NorthStar Policy NEU-009 section 2.4" },
        { id: "c3", text: "Failure of initial management where applicable", status: "met", rationale: "Analgesic trial without relief.", citation: "NorthStar Policy NEU-009 section 3.0" },
      ],
      missingItems: [],
    },
    submission: {
      status: "acknowledged",
      portal: "NorthStar Provider Portal",
      robot: "Portal Submit Robot",
      portalRef: "NSM-AUTH-771028",
      submittedAt: ago(60 * 22),
    },
    decision: {
      outcome: "denied",
      denialCode: "MN-204",
      reason:
        "Payer automated review denied citing insufficient documentation of red-flag symptoms. Determination did not reference the documented papilledema or focal deficit.",
      decidedAt: ago(60 * 5),
    },
    appeal: {
      status: "awaiting_signoff",
      draftedAt: ago(6),
      citations: [
        "NorthStar Policy NEU-009 section 2.1",
        "ACR Appropriateness Criteria: Headache (variant with neurologic deficit)",
        "Documented papilledema, Neuro note 2026-06-02",
      ],
      draftLetter:
        "RE: Appeal of Prior Authorization Denial - Eleanor Briggs, MRN-220471\nAuthorization reference: NSM-AUTH-771028\nProcedure: MRI brain with and without contrast (CPT 70553)\n\nDear Medical Director,\n\nWe respectfully appeal the denial dated above. The denial cited insufficient documentation of red-flag symptoms, but the medical record clearly documents two red-flag findings that satisfy NorthStar Policy NEU-009 section 2.1: new papilledema on fundoscopic exam and a focal neurologic deficit (right facial droop). A prior CT was reviewed and recommended MRI characterization, satisfying section 2.4, and an analgesic trial failed, satisfying section 3.0.\n\nThe ACR Appropriateness Criteria for headache with a neurologic deficit rate MRI of the brain as usually appropriate. Delaying this study risks missing a treatable intracranial process in a 67-year-old patient with progressive symptoms.\n\nWe ask that the denial be overturned and the authorization approved. Supporting documentation is enclosed.\n\nThis appeal was prepared for clinician review and is pending sign-off by Dr. Helen Yoo before submission.\n\nSincerely,\nUtilization Review, on behalf of Dr. Omar Haddad",
    },
    humanTasks: [
      {
        id: "ht-20455-1",
        title: "Approve submission to NorthStar",
        description: "Submission approval signed by clinician.",
        kind: "submission_approval",
        assignee: "Dr. Helen Yoo",
        status: "approved",
        createdAt: ago(60 * 23),
        decidedAt: ago(60 * 22 - 10),
        note: "Strong red-flag presentation. Approved.",
      },
      {
        id: "ht-20455-2",
        title: "Sign off on appeal letter before it is sent",
        description:
          "The appeal agent drafted a citation-backed letter contesting the automated denial. By law a clinician must review and sign before anything is sent to the payer.",
        kind: "appeal_signoff",
        assignee: "Dr. Helen Yoo",
        status: "open",
        createdAt: ago(6),
      },
    ],
    auditTrail: [
      ev(60 * 26, "coordinator", "Devon Clarke", "Case opened", "Urgent brain MRI referral entered.", "intake"),
      ev(60 * 25, "agent", "Clinical Evidence Agent (Agent Builder)", "Evidence extracted", "Pulled papilledema, focal deficit, prior CT.", "evidence"),
      ev(60 * 24, "agent", "Payer-Rules Agent (CrewAI)", "Policy matched", "All criteria met against NEU-009.", "rule_match"),
      ev(60 * 22 - 10, "clinician", "Dr. Helen Yoo", "Submission approved", "Signed off at human gate.", "submission"),
      ev(60 * 22, "robot", "Portal Submit Robot (RPA)", "Submitted to portal", "Filed to NorthStar, reference NSM-AUTH-771028.", "submission"),
      ev(60 * 5, "robot", "Status Poll Robot (RPA)", "Decision received: DENIED", "Payer automated review returned denial MN-204.", "decision"),
      ev(60 * 5 - 1, "system", "Maestro Case Manager", "Stage advanced: Appeal", "Denial triggered automatic advance to the appeal stage.", "appeal"),
      ev(6, "agent", "Appeal Drafting Agent", "Appeal letter drafted", "Citation-backed appeal generated. Case paused at human task for clinician sign-off.", "appeal"),
      ev(6, "system", "Maestro Case Manager", "Case paused (waiting on human)", "No outbound action until Dr. Helen Yoo signs the appeal.", "appeal"),
    ],
  },
  {
    id: "PA-20444",
    title: "Lumbar spine MRI (approved)",
    patient: { name: "Grace Liu", mrn: "MRN-118274", dob: "1979-12-05", age: 46, sex: "F" },
    procedure: { cpt: "72148", name: "MRI lumbar spine without contrast", site: "Lumbar spine" },
    primaryDiagnosis: { icd10: "M54.16", name: "Radiculopathy, lumbar region" },
    payer: { id: "meridian", name: "Meridian Health Plan", plan: "Meridian PPO Select" },
    referringProvider: { name: "Dr. Aisha Rahman", npi: "1730284417", specialty: "Orthopedics" },
    urgency: "routine",
    stage: "decision",
    runState: "running",
    createdAt: ago(60 * 20),
    updatedAt: ago(60 * 2),
    slaDueAt: ahead(60 * 40),
    coordinator: "Priya Nair",
    clinician: "Dr. Marcus Bell",
    estimatedValue: 1450,
    evidence: {
      status: "extracted",
      model: "Claude via UiPath AI Trust Layer",
      extractedAt: ago(60 * 19),
      narrative:
        "46-year-old female with 10 weeks of lumbar radiculopathy. Failed conservative therapy including PT and NSAIDs. Lumbar X-ray on file from 2026-05-01. Positive neuro findings on exam.",
      diagnoses: [{ icd10: "M54.16", name: "Radiculopathy, lumbar region" }],
      priorTreatments: [
        { id: "t1", label: "Physical therapy", value: "10 weeks", source: "PT note", confidence: 0.96 },
        { id: "t2", label: "NSAID trial", value: "Ibuprofen 6 weeks", source: "Medication list", confidence: 0.94 },
      ],
      documents: [
        { id: "d1", label: "Lumbar X-ray", value: "On file 2026-05-01", source: "Radiology report", confidence: 0.97 },
        { id: "d2", label: "Neuro exam", value: "Positive SLR", source: "Progress note", confidence: 0.9 },
      ],
    },
    ruleMatch: {
      status: "matched",
      payerPolicy: "Advanced Imaging - MRI of the Spine",
      policyId: "MERIDIAN-RAD-014",
      framework: "CrewAI payer-rules crew (UiPath governed)",
      confidence: 0.95,
      readiness: 100,
      matchedAt: ago(60 * 18),
      criteria: [
        { id: "c1", text: "Conservative therapy of at least 6 weeks documented and failed", status: "met", rationale: "10 weeks PT plus NSAIDs.", citation: "Meridian Medical Policy RAD-014 section 3.2" },
        { id: "c2", text: "Neurologic deficit or red-flag symptom documented", status: "met", rationale: "Positive SLR.", citation: "Meridian Medical Policy RAD-014 section 3.3" },
        { id: "c3", text: "Recent radiographs (X-ray) on file within 60 days", status: "met", rationale: "Lumbar X-ray on file 2026-05-01.", citation: "Meridian Medical Policy RAD-014 section 4.1" },
      ],
      missingItems: [],
    },
    submission: {
      status: "acknowledged",
      portal: "Meridian Provider Portal",
      robot: "Portal Submit Robot",
      portalRef: "MER-AUTH-118901",
      submittedAt: ago(60 * 16),
    },
    decision: {
      outcome: "approved",
      reason: "Approved. All medical-necessity criteria satisfied on first pass.",
      decidedAt: ago(60 * 2),
    },
    appeal: { status: "none", citations: [] },
    humanTasks: [
      {
        id: "ht-20444-1",
        title: "Approve submission to Meridian",
        description: "Submission approval signed by clinician.",
        kind: "submission_approval",
        assignee: "Dr. Marcus Bell",
        status: "approved",
        createdAt: ago(60 * 17),
        decidedAt: ago(60 * 16 - 20),
        note: "Clean case, all criteria met. Approved.",
      },
    ],
    auditTrail: [
      ev(60 * 20, "coordinator", "Priya Nair", "Case opened", "Lumbar MRI referral entered.", "intake"),
      ev(60 * 19, "agent", "Clinical Evidence Agent (Agent Builder)", "Evidence extracted", "All required evidence found including X-ray.", "evidence"),
      ev(60 * 18, "agent", "Payer-Rules Agent (CrewAI)", "Policy matched", "All criteria met. Readiness 100%.", "rule_match"),
      ev(60 * 16 - 20, "clinician", "Dr. Marcus Bell", "Submission approved", "Signed off at human gate.", "submission"),
      ev(60 * 16, "robot", "Portal Submit Robot (RPA)", "Submitted to portal", "Filed to Meridian, reference MER-AUTH-118901.", "submission"),
      ev(60 * 2, "robot", "Status Poll Robot (RPA)", "Decision received: APPROVED", "Payer approved on first pass.", "decision"),
    ],
  },
  {
    id: "PA-20431",
    title: "Knee arthroscopy (closed, approved)",
    patient: { name: "Hassan Pereira", mrn: "MRN-905512", dob: "1992-07-19", age: 33, sex: "M" },
    procedure: { cpt: "29880", name: "Arthroscopy, knee, with meniscectomy (medial and lateral)", site: "Left knee" },
    primaryDiagnosis: { icd10: "M23.206", name: "Derangement of meniscus, left knee" },
    payer: { id: "gulfcoast", name: "Gulf Coast Care", plan: "Gulf Coast EPO" },
    referringProvider: { name: "Dr. Rachel Stern", npi: "1556372819", specialty: "Orthopedic Surgery" },
    urgency: "routine",
    stage: "closed",
    runState: "running",
    createdAt: ago(60 * 70),
    updatedAt: ago(60 * 30),
    slaDueAt: ago(60 * 40),
    coordinator: "Devon Clarke",
    clinician: "Dr. Marcus Bell",
    estimatedValue: 6400,
    evidence: {
      status: "extracted",
      model: "Claude via UiPath AI Trust Layer",
      extractedAt: ago(60 * 69),
      narrative: "33-year-old male, confirmed meniscus tear on MRI, failed PT and bracing. Functional limitation on exam.",
      diagnoses: [{ icd10: "M23.206", name: "Derangement of meniscus, left knee" }],
      priorTreatments: [{ id: "t1", label: "Physical therapy", value: "8 weeks", source: "PT note", confidence: 0.95 }],
      documents: [{ id: "d1", label: "Knee MRI", value: "Meniscus tear confirmed", source: "Radiology", confidence: 0.97 }],
    },
    ruleMatch: {
      status: "matched",
      payerPolicy: "Knee Arthroscopy and Joint Procedures",
      policyId: "GULFCOAST-ORT-022",
      framework: "CrewAI payer-rules crew (UiPath governed)",
      confidence: 0.95,
      readiness: 100,
      matchedAt: ago(60 * 68),
      criteria: [
        { id: "c1", text: "MRI or imaging confirming structural pathology", status: "met", rationale: "MRI confirms tear.", citation: "Gulf Coast Policy ORT-022 section 1.2" },
        { id: "c2", text: "Conservative therapy trial of 6 weeks documented", status: "met", rationale: "8 weeks PT.", citation: "Gulf Coast Policy ORT-022 section 2.1" },
        { id: "c3", text: "Functional limitation documented on exam", status: "met", rationale: "Limitation documented.", citation: "Gulf Coast Policy ORT-022 section 2.3" },
      ],
      missingItems: [],
    },
    submission: { status: "acknowledged", portal: "Gulf Coast Provider Portal", robot: "Portal Submit Robot", portalRef: "GCC-AUTH-905901", submittedAt: ago(60 * 60) },
    decision: { outcome: "approved", reason: "Approved on first pass.", decidedAt: ago(60 * 31) },
    appeal: { status: "none", citations: [] },
    humanTasks: [
      { id: "ht-20431-1", title: "Approve submission to Gulf Coast", description: "Submission approval signed by clinician.", kind: "submission_approval", assignee: "Dr. Marcus Bell", status: "approved", createdAt: ago(60 * 65), decidedAt: ago(60 * 61), note: "Approved." },
    ],
    auditTrail: [
      ev(60 * 70, "coordinator", "Devon Clarke", "Case opened", "Knee arthroscopy referral.", "intake"),
      ev(60 * 69, "agent", "Clinical Evidence Agent (Agent Builder)", "Evidence extracted", "MRI and PT documented.", "evidence"),
      ev(60 * 68, "agent", "Payer-Rules Agent (CrewAI)", "Policy matched", "All criteria met.", "rule_match"),
      ev(60 * 61, "clinician", "Dr. Marcus Bell", "Submission approved", "Signed at human gate.", "submission"),
      ev(60 * 60, "robot", "Portal Submit Robot (RPA)", "Submitted to portal", "Filed, GCC-AUTH-905901.", "submission"),
      ev(60 * 31, "robot", "Status Poll Robot (RPA)", "Decision received: APPROVED", "Approved on first pass.", "decision"),
      ev(60 * 30, "system", "Maestro Case Manager", "Case closed", "Authorization approved and archived.", "closed"),
    ],
  },
  {
    id: "PA-20419",
    title: "Brain MRI (closed, won on appeal)",
    patient: { name: "Marisol Vega", mrn: "MRN-660318", dob: "1963-04-27", age: 63, sex: "F" },
    procedure: { cpt: "70553", name: "MRI brain with and without contrast", site: "Brain" },
    primaryDiagnosis: { icd10: "R51.9", name: "Headache, unspecified" },
    payer: { id: "northstar", name: "NorthStar Mutual", plan: "NorthStar HMO Plus" },
    referringProvider: { name: "Dr. Omar Haddad", npi: "1902837465", specialty: "Neurology" },
    urgency: "urgent",
    stage: "closed",
    runState: "running",
    createdAt: ago(60 * 96),
    updatedAt: ago(60 * 40),
    slaDueAt: ago(60 * 60),
    coordinator: "Devon Clarke",
    clinician: "Dr. Helen Yoo",
    estimatedValue: 1320,
    evidence: {
      status: "extracted",
      model: "Claude via UiPath AI Trust Layer",
      extractedAt: ago(60 * 95),
      narrative: "63-year-old female with focal deficit and abnormal prior CT. Met medical necessity. Initial automated denial overturned on clinician-signed appeal.",
      diagnoses: [{ icd10: "R51.9", name: "Headache, unspecified" }],
      priorTreatments: [{ id: "t1", label: "Analgesic trial", value: "No relief", source: "Medication list", confidence: 0.9 }],
      documents: [{ id: "d1", label: "Prior CT", value: "Abnormal finding", source: "Radiology", confidence: 0.95 }],
    },
    ruleMatch: {
      status: "matched",
      payerPolicy: "MRI of the Brain - Medical Necessity",
      policyId: "NORTHSTAR-NEU-009",
      framework: "CrewAI payer-rules crew (UiPath governed)",
      confidence: 0.96,
      readiness: 100,
      matchedAt: ago(60 * 94),
      criteria: [
        { id: "c1", text: "Documented new or progressive neurologic symptoms", status: "met", rationale: "Focal deficit.", citation: "NorthStar Policy NEU-009 section 2.1" },
        { id: "c2", text: "Prior CT or imaging reviewed and documented", status: "met", rationale: "Abnormal CT.", citation: "NorthStar Policy NEU-009 section 2.4" },
        { id: "c3", text: "Failure of initial management where applicable", status: "met", rationale: "Analgesic failed.", citation: "NorthStar Policy NEU-009 section 3.0" },
      ],
      missingItems: [],
    },
    submission: { status: "acknowledged", portal: "NorthStar Provider Portal", robot: "Portal Submit Robot", portalRef: "NSM-AUTH-660901", submittedAt: ago(60 * 90) },
    decision: { outcome: "approved", reason: "Initial denial overturned after clinician-signed appeal.", decidedAt: ago(60 * 41) },
    appeal: {
      status: "overturned",
      draftedAt: ago(60 * 70),
      signedBy: "Dr. Helen Yoo",
      signedAt: ago(60 * 68),
      citations: ["NorthStar Policy NEU-009 section 2.1", "ACR Appropriateness Criteria: Headache"],
      draftLetter:
        "RE: Appeal of Prior Authorization Denial - Marisol Vega, MRN-660318\n\nThe denial overlooked the documented focal neurologic deficit and abnormal prior CT, both of which satisfy NorthStar NEU-009 section 2.1 and 2.4. We requested the denial be overturned. Signed by Dr. Helen Yoo.",
    },
    humanTasks: [
      { id: "ht-20419-1", title: "Approve submission to NorthStar", description: "Submission approval.", kind: "submission_approval", assignee: "Dr. Helen Yoo", status: "approved", createdAt: ago(60 * 93), decidedAt: ago(60 * 91), note: "Approved." },
      { id: "ht-20419-2", title: "Sign off on appeal letter", description: "Appeal sign-off.", kind: "appeal_signoff", assignee: "Dr. Helen Yoo", status: "approved", createdAt: ago(60 * 70), decidedAt: ago(60 * 68), note: "Clear red-flag case. Signed and submitted appeal." },
    ],
    auditTrail: [
      ev(60 * 96, "coordinator", "Devon Clarke", "Case opened", "Urgent brain MRI referral.", "intake"),
      ev(60 * 95, "agent", "Clinical Evidence Agent (Agent Builder)", "Evidence extracted", "Focal deficit and abnormal CT documented.", "evidence"),
      ev(60 * 94, "agent", "Payer-Rules Agent (CrewAI)", "Policy matched", "All criteria met.", "rule_match"),
      ev(60 * 91, "clinician", "Dr. Helen Yoo", "Submission approved", "Signed at human gate.", "submission"),
      ev(60 * 90, "robot", "Portal Submit Robot (RPA)", "Submitted to portal", "Filed, NSM-AUTH-660901.", "submission"),
      ev(60 * 80, "robot", "Status Poll Robot (RPA)", "Decision received: DENIED", "Automated denial returned.", "decision"),
      ev(60 * 70, "agent", "Appeal Drafting Agent", "Appeal drafted", "Citation-backed appeal generated for review.", "appeal"),
      ev(60 * 68, "clinician", "Dr. Helen Yoo", "Appeal signed", "Clinician signed off and appeal submitted.", "appeal"),
      ev(60 * 41, "robot", "Status Poll Robot (RPA)", "Decision received: OVERTURNED", "Appeal won, authorization approved.", "decision"),
      ev(60 * 40, "system", "Maestro Case Manager", "Case closed", "Authorization approved after appeal and archived.", "closed"),
    ],
  },
];
